export { default as About } from './about/About'
export { default as Collection } from './collection/Collection'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as Instagram } from './instagram/Instagram'